#ifndef SOCK_ERRORS
#define SOCK_ERRORS

#ifdef _WIN32
	#define SOCK_ADDRINUSE		WSAEADDRINUSE

	#define SOCK_WOULDBLOCK		WSAEWOULDBLOCK
	#define SOCK_ALREADY		WSAEALREADY
	#define SOCK_ISCONN			WSAEISCONN
	#define SOCK_INVAL			WSAEINVAL
	#define SOCK_INPROGRESS		WSAEINPROGRESS
	#define SOCK_CONNRESET		WSAECONNRESET
	#define SOCK_ADDRNOTAVAIL	WSAEADDRNOTAVAIL
	#define SOCK_AFNOSUPPORT	WSAEAFNOSUPPORT
	#define SOCK_CONNABORTED	WSAECONNABORTED
	#define SOCK_CONNREFUSED	WSAECONNREFUSED
	#define SOCK_DESTADDRREQ	WSAEDESTADDRREQ
	#define SOCK_FAULT			WSAEFAULT
	#define SOCK_HOSTDOWN		WSAEHOSTDOWN
	#define SOCK_HOSTUNREACH	WSAEHOSTUNREACH
	#define SOCK_MFILE			WSAEMFILE
	#define SOCK_MSGSIZE		WSAEMSGSIZE
	#define SOCK_NETDOWN		WSAENETDOWN
	#define SOCK_NETRESET		WSAENETRESET
	#define SOCK_NETUNREACH		WSAENETUNREACH
	#define SOCK_NOBUFS			WSAENOBUFS
	#define SOCK_NOTCONN		WSAENOTCONN
	#define SOCK_NOTSOCK		WSAENOTSOCK
	#define SOCK_PFNOSUPPORT	WSAEPFNOSUPPORT
	#define SOCK_SHUTDOWN		WSAESHUTDOWN
	#define SOCK_TIMEDOUT		WSAETIMEDOUT
	#define SOCK_HOST_NOT_FOUND	WSAHOST_NOT_FOUND
	#define SOCK_NO_RECOVERY	WSANO_RECOVERY
	#define SOCK_TRY_AGAIN		WSATRY_AGAIN
	//Winsock specific

	#define SOCK_PROCLIM			WSAEPROCLIM
	#define SOCK_NOTINITIALISED		WSANOTINITIALISED
	#define SOCK_SYSNOTREADY		WSASYSNOTREADY
	#define SOCK_VERNOTSUPPORTED	WSAVERNOTSUPPORTED
#else
	#define SOCK_WOULDBLOCK		EAGAIN
	#define SOCK_ALREADY		EALREADY
	#define SOCK_ISCONN			EISCONN
	#define SOCK_INVAL			EINVAL
	#define SOCK_INPROGRESS		EINPROGRESS
	#define SOCK_CONNRESET		ECONNRESET
	#define SOCK_ADDRINUSE		EADDRINUSE
	#define SOCK_ADDRNOTAVAIL	EADDRNOTAVAIL
	#define SOCK_AFNOSUPPORT	EAFNOSUPPORT
	#define SOCK_CONNABORTED	ECONNABORTED
	#define SOCK_CONNREFUSED	ECONNREFUSED
	#define SOCK_DESTADDRREQ	EDESTADDRREQ
	#define SOCK_FAULT			EFAULT
	#define SOCK_HOSTDOWN		EHOSTDOWN
	#define SOCK_HOSTUNREACH	EHOSTUNREACH
	#define SOCK_MFILE			EMFILE
	#define SOCK_MSGSIZE		EMSGSIZE
	#define SOCK_NETDOWN		ENETDOWN
	#define SOCK_NETRESET		ENETRESET
	#define SOCK_NETUNREACH		ENETUNREACH
	#define SOCK_NOBUFS			ENOBUFS
	#define SOCK_NOTCONN		ENOTCONN
	#define SOCK_NOTSOCK		ENOTSOCK
	#define SOCK_PFNOSUPPORT	EPFNOSUPPORT
	#define SOCK_SHUTDOWN		ESHUTDOWN
	#define SOCK_TIMEDOUT		ETIMEDOUT
	#define SOCK_HOST_NOT_FOUND	HOST_NOT_FOUND
	#define SOCK_NO_RECOVERY	NO_RECOVERY
	#define SOCK_TRY_AGAIN		TRY_AGAIN
#endif

#endif //ndef SOCK_ERRORS